apps = {
    '296':'OKR - APRENDIZADOS - PRODUÇÃO',
    '289':'OKR - DESDOBRAMENTO DE DIRETORIAS - PRODUÇÃO',
    '315':'OKR - KR - META - COMERCIAL R$ - PRODUÇÃO',
    '290':'OKR - KR - META - GERAL - PRODUÇÃO',
    '292':'OKR - KR - META - INDIVIDUAL - PRODUÇÃO',
    '282':'OKR - PLANO DE AÇÃO - PRODUÇÃO',
    '283':'OKR - REVISAR META - PRODUÇÃO',
    '320':'OKR - FATURAMENTO POR CONTRATO',
    }

replace_emails = {
    'ADRIANA.FONSECA@NMCINTEGRATIVA.COM.BR':'ADRIANA FONSECA',
    'ADRIANA.GIOVANA@NMCINTEGRATIVA.COM.BR':'ADRIANA GIOVANA',
    'ADMINISTRATIVO.DDIAT@NMCINTEGRATIVA.COM.BR':'AMANDA KETILEY SOUZA SANTOS',
    'ANA.CECILIA@NMCINTEGRATIVA.COM.BR':'ANA CECÍLIA GOMES DE PAULA',
    'CONTATO@NMCINTEGRATIVA.COM.BR':'ANNA CAROLINA',
    'ANTONIO@SKENE.COM.BR':'ANTONIO LOURENÇO',
    'BERENICE@NMCINTEGRATIVA.COM.BR':'BERENICE BRAGA MARGARIDA',
    'BRUNO.GOMES@NMCINTEGRATIVA.COM.BR':'BRUNO DOS SANTOS GOMES',
    'CATIA.SILENE@NMCINTEGRATIVA.COM.BR':'CÁTIA SILENE',
    'CLAUDIA@NMCINTEGRATIVA.COM.BR':'CLÁUDIA LEITE',
    'CLEBER.RIBEIRO@NMCINTEGRATIVA.COM.BR':'CLEBER RIBEIRO',
    'DANIEL.PIRES@NMCINTEGRATIVA.COM.BR':'DANIEL PIRES',
    'ELAINE.ANJOS@NMCINTEGRATIVA.COM.BR':'ELAINE ANJOS',
    'ELIANE.MESQUITA@NMCINTEGRATIVA.COM.BR':'ELIANE MESQUITA',
    'FABIO.MOURA@NMCINTEGRATIVA.COM.BR':'FÁBIO MOURA',
    'BACIAS@NMCINTEGRATIVA.COM.BR':'FELIPE SAMPAIO MATTA',
    'FERNANDA.MENDES@NMCINTEGRATIVA.COM.BR':'FERNANDA MENDES',
    'FERNANDO.FERRARI@NMCINTEGRATIVA.COM.BR':'FERNANDO FERRARI',
    'FERNANDO.RODRIGUES@NMCINTEGRATIVA.COM.BR':'FERNANDO RODRIGUES',
    'PESSOAL@NMCINTEGRATIVA.COM.BR':'GRAZIELE BARBOSA',
    'HELENO@NMCINTEGRATIVA.COM.BR':'HELENO MACIEL',
    'HENRIQUE.NAHUM@NMCINTEGRATIVA.COM.BR':'HENRIQUE GARIGLIO NAHUM',
    'IGORCOMERCIAL@NMCINTEGRATIVA.COM.BR':'IGOR ALVES CRISCUOLO',
    'JACQUELINE@NMCINTEGRATIVA.COM.BR':'JACQUELINE ROSA',
    'JADSON@NMCINTEGRATIVA.COM.BR':'JADSON REIS',
    'JANICE@NMCINTEGRATIVA.COM.BR':'JANICE OLIVEIRA',
    'JOAO.GONCALVES@NMCINTEGRATIVA.COM.BR':'JOÃO VITOR DE ASSIS GONZAGA GONÇALVES',
    'JULIANA.SOUZA@NMCINTEGRATIVA.COM.BR':'JULIANA SOUZA',
    'JULIANA.TRINDADE@NMCINTEGRATIVA.COM.BR':'JULIANA TRINDADE',
    'KELLY.SILVA@NMCINTEGRATIVA.COM.BR':'KELLY SILVA',
    'LEANDRO.BELINI@NMCINTEGRATIVA.COM.BR':'LEANDRO BELINI',
    'LILIANE.FERREIRA@NMCINTEGRATIVA.COM.BR':'LILIANE FERREIRA',
    'LINO@NMCINTEGRATIVA.COM.BR':'LINO RAMOS',
    'LUCAS@NMCINTEGRATIVA.COM.BR':'LUCAS TANNURE',
    'RH@NMCINTEGRATIVA.COM.BR':'LUCIANA LEITE',
    'LUCIANA.FINANCEIRO@NMCINTEGRATIVA.COM.BR':'LUCIANA PAIXÃO',
    'LUDMILA.COSTA@NMCINTEGRATIVA.COM.BR':'LUDMILA COSTA',
    'ADMINISTRATIVO.DASA@NMCINTEGRATIVA.COM.BR ':'MARCELINA MANUELA DOS SANTOS',
    'MARCELO@NMCINTEGRATIVA.COM.BR':'MARCELO ANDRADE',
    'MARCOLANA@NMCINTEGRATIVA.COM.BR':'MARCO ANTONIO LANA',
    'MARCUS.LAGE@NMCINTEGRATIVA.COM.BR':'MARCUS LAGE',
    'ALICE.HENNE@NMCINTEGRATIVA.COM.BR':'MARIA ALICE',
    'GRACA.BIBIANO@NMCINTEGRATIVA.COM.BR':'MARIA DAS GRAÇAS BIBIANO',
    'MARIA.RITA@NMCINTEGRATIVA.COM.BR':'MARIA RITA',
    'MARIA.TEREZA@NMCINTEGRATIVA.COM.BR':'MARIA TEREZA',
    'MARIANA@NMCINTEGRATIVA.COM.BR':'MARIANA NAHAS',
    'MARIANA.RIBEIRO@NMCINTEGRATIVA.COM.BR':'MARIANA RIBEIRO',
    'ADM.CMD@NMCINTEGRATIVA.COM.BR':'MARIANA SALDANHA',
    'MARINA.SCHUH@NMCINTEGRATIVA.COM.BR':'MARINA SCHUH',
    'MILENE.SOUTO@NMCINTEGRATIVA.COM.BR':'MILENE SOUTO',
    'MIRO@NMCINTEGRATIVA.COM.BR':'MIRO AUGUSTO',
    'OSWALDO.DEHON@NMCINTEGRATIVA.COM.BR':'OSWALDO DEHON',
    'PAOLA.FERREIRA@NMCINTEGRATIVA.COM.BR':'PAOLA FERREIRA',
    'PATRICIA.SOARES@NMCINTEGRATIVA.COM.BR':'PATRICIA SOARES',
    'COMERCIAL@NMCINTEGRATIVA.COM.BR':'PAULA GRIS',
    'PEDRO.REIS@NMCINTEGRATIVA.COM.BR':'PEDRO REIS',
    'RICARDO@NMCINTEGRATIVA.COM.BR':'RICARDO OLIVEIRA',
    'ROSELY.CALDEIRA@NMCINTEGRATIVA.COM.BR':'ROSELY CALDEIRA',
    'SERGIO.OLIVEIRA@NMCINTEGRATIVA.COM.BR':'SÉRGIO OLIVEIRA',
    'ADMINISTRATIVO.MATRIZ@NMCINTEGRATIVA.COM.BR':'SILVANIA OLIVEIRA',
    'SILVIA.ZAMAI@NMCINTEGRATIVA.COM.BR':'SILVIA ZAMAI',
    'SIMONE.FRANCISCO@NMCINTEGRATIVA.COM.BR':'SIMONE FRANCISCO',
    'MARACANA@NMCINTEGRATIVA.COM.BR':'TATIANE FIGUEREDO',
    'THAIS.PIRES@NMCINTEGRATIVA.COM.BR':'THAIS PIRES',
    'WALLACE.ARAUJO@NMCINTEGRATIVA.COM.BR':'WALLACE ARAUJO',
    'CARLOS.LONGINO@NMCINTEGRATIVA.COM.BR': 'CARLOS LONGINO',
}

tipo_medida = {'UNIDADE MONETÁRIA (R$)':['nivelDeDesdobramento','masterInstanceId','colaboradorResponsavel', 'diretoria',
                                        'diretoriasQueParticipamDessaMeta','descricaoDaMetaMensal',
                                        'frequenciaDeMensuracao','periodo', 'kR', 'metaIndividual', 'oKR', 'peso',
                                        'cumpriuAMetamoeda', 'periodoDeAvaliacaomoeda', 'resultadoAlcancadomoeda', 'totalAcumulado'],

                'QUANTIDADE (UND.)':['nivelDeDesdobramento','masterInstanceId','colaboradorResponsavel', 'diretoria',
                                        'diretoriasQueParticipamDessaMeta','descricaoDaMetaMensal',
                                        'frequenciaDeMensuracao','periodo', 'kR', 'metaIndividual', 'oKR', 'peso',
                                        'cumpriuAMetaqtd', 'periodoDeAvaliacaoqtd', 'resultadoAlcancadoQtd', 'totalAcumuladoqtd'],
                                        
                'PORCENTAGEM (%)':['nivelDeDesdobramento','masterInstanceId','colaboradorResponsavel', 'diretoria',
                                        'diretoriasQueParticipamDessaMeta','descricaoDaMetaMensal',
                                        'frequenciaDeMensuracao','periodo', 'kR', 'metaIndividual', 'oKR', 'peso',
                                        'cumpriuAMetaporc', 'periodoDeAvaliacaoporc', 'resultadoAlcancadoporc', 'totalAcumuladoporc'],

                'ENTREGÁVEL (SIM/NÃO)':['nivelDeDesdobramento','masterInstanceId','colaboradorResponsavel', 'diretoria',
                                        'diretoriasQueParticipamDessaMeta','descricaoDaMetaMensal',
                                        'frequenciaDeMensuracao','periodo', 'kR', 'metaIndividual', 'oKR', 'peso',
                                         'periodoDeAvaliacaoentreg', 'resultadoAlcancadoSimnaoentreg']}

campo_vazio_medida = {'UNIDADE MONETÁRIA (R$)': ['cumpriuAMetamoeda', 'periodoDeAvaliacaomoeda', 'resultadoAlcancadomoeda', 'totalAcumulado'],
                    'QUANTIDADE (UND.)': ['cumpriuAMetaqtd', 'periodoDeAvaliacaoqtd', 'resultadoAlcancadoQtd', 'totalAcumuladoqtd'],
                    'PORCENTAGEM (%)': ['cumpriuAMetaporc', 'periodoDeAvaliacaoporc', 'resultadoAlcancadoporc', 'totalAcumuladoporc'],
                    'ENTREGÁVEL (SIM/NÃO)': ['periodoDeAvaliacaoentreg', 'resultadoAlcancadoSimnaoentreg']}

diretorias_list = [
    'DIRETORIA DE DESENVOLVIMENTO AMBIENTAL, SANEAMENTO E AGROECOLOGIA - DASA',
    'DIRETORIA ADMINISTRATIVA FINANCEIRA - DAF',
    'DIRETORIA DE SOCIOECONOMIA E ENGAJAMENTO - DES',
    'DIRETORIA DE NEGÓCIOS PÚBLICOS - DPUB',
    'DIRETORIA COMERCIAL - DCOM',
    'DIRETORIA DE DESLOCAMENTO INVOLUNTÁRIO E ANÁLISES TERRITORIAIS - DDIAT',
    'Gerência de Agronegócios - GAGR'
]

gatilhos_diretorias = {
    'DASA':['15,9 MM', '4,7 MM', '1.05'],
    'DAF':['75 MM', '32 MM', '4.80'],
    'DES':['22 MM', '11,6 MM', '2.32'],
    'DPUB':['8,8 MM', '5 MM', '0.65'],
    'DCOM':['75 MM', '32 MM', '4.80'],
    'DDIAT':['27,5 MM', '12,89 MM', '2.52'],
    'DRF':['0,0 MM', '0,0 MM', '0,0%'],
    'GAGR':['0,0 MM', '0,0 MM', "0,0"],
}


diretorias_dic = {
     'DIRETORIA DE DESENVOLVIMENTO AMBIENTAL, SANEAMENTO E AGROECOLOGIA - DASA':'DASA',
     'DIRETORIA ADMINISTRATIVA FINANCEIRA - DAF':'DAF',
       'DIRETORIA DE SOCIOECONOMIA E ENGAJAMENTO - DES':'DES',
      'DIRETORIA DE NEGÓCIOS PÚBLICOS - DPUB':'DPUB',
      'DIRETORIA COMERCIAL - DCOM':'DCOM',
      'DIRETORIA DE DESLOCAMENTO INVOLUNTÁRIO E ANÁLISES TERRITORIAIS - DDIAT':'DDIAT',
      'DIRETORIA REGULARIZAÇÃO FUNDIÁRIA E COMPRA ASSISTIDA - DRF':'DRF',
      'Gerência de Agronegócios - GAGR' : 'GAGR',
      
    }

usuarios_master = ['Mariana',
               # 'Ricardo Oliveira',
                'Antonio Nahas',
                'Henrique',]

nvl_acesso_app = {
    'Mariana':[
                'DIRETORIA DE DESENVOLVIMENTO AMBIENTAL, SANEAMENTO E AGROECOLOGIA - DASA',
                'DIRETORIA ADMINISTRATIVA FINANCEIRA - DAF',
                'DIRETORIA DE SOCIOECONOMIA E ENGAJAMENTO - DES',
                'DIRETORIA DE NEGÓCIOS PÚBLICOS - DPUB',
                'DIRETORIA COMERCIAL - DCOM',
                'DIRETORIA DE DESLOCAMENTO INVOLUNTÁRIO E ANÁLISES TERRITORIAIS - DDIAT',
                'DIRETORIA REGULARIZAÇÃO FUNDIÁRIA E COMPRA ASSISTIDA - DRF'
    ],
    'Ricardo Oliveira':[
                'DIRETORIA DE DESENVOLVIMENTO AMBIENTAL, SANEAMENTO E AGROECOLOGIA - DASA',
                'DIRETORIA ADMINISTRATIVA FINANCEIRA - DAF',
                'DIRETORIA DE SOCIOECONOMIA E ENGAJAMENTO - DES',
                'DIRETORIA DE NEGÓCIOS PÚBLICOS - DPUB',
                'DIRETORIA COMERCIAL - DCOM',
                'DIRETORIA DE DESLOCAMENTO INVOLUNTÁRIO E ANÁLISES TERRITORIAIS - DDIAT',
                'DIRETORIA REGULARIZAÇÃO FUNDIÁRIA E COMPRA ASSISTIDA - DRF'
    ],
    'Janice':[
                'DIRETORIA ADMINISTRATIVA FINANCEIRA - DAF'
    ],
    'Miro':[
                'DIRETORIA DE DESLOCAMENTO INVOLUNTÁRIO E ANÁLISES TERRITORIAIS - DDIAT'
    ],
    'Maria Alice':[
                'DIRETORIA DE SOCIOECONOMIA E ENGAJAMENTO - DES'
    ],
    'Heleno Maciel':[
                'DIRETORIA DE NEGÓCIOS PÚBLICOS - DPUB',
                'DIRETORIA DE DESLOCAMENTO INVOLUNTÁRIO E ANÁLISES TERRITORIAIS - DDIAT'
    ],
    'Antonio Nahas':[
                'DIRETORIA DE DESENVOLVIMENTO AMBIENTAL, SANEAMENTO E AGROECOLOGIA - DASA',
                'DIRETORIA ADMINISTRATIVA FINANCEIRA - DAF',
                'DIRETORIA DE SOCIOECONOMIA E ENGAJAMENTO - DES',
                'DIRETORIA DE NEGÓCIOS PÚBLICOS - DPUB',
                'DIRETORIA COMERCIAL - DCOM',
                'DIRETORIA DE DESLOCAMENTO INVOLUNTÁRIO E ANÁLISES TERRITORIAIS - DDIAT',
                'DIRETORIA REGULARIZAÇÃO FUNDIÁRIA E COMPRA ASSISTIDA - DRF',
    ],
    'Henrique':[
                'DIRETORIA DE DESENVOLVIMENTO AMBIENTAL, SANEAMENTO E AGROECOLOGIA - DASA',
                'DIRETORIA ADMINISTRATIVA FINANCEIRA - DAF',
                'DIRETORIA DE SOCIOECONOMIA E ENGAJAMENTO - DES',
                'DIRETORIA DE NEGÓCIOS PÚBLICOS - DPUB',
                'DIRETORIA COMERCIAL - DCOM',
                'DIRETORIA DE DESLOCAMENTO INVOLUNTÁRIO E ANÁLISES TERRITORIAIS - DDIAT',
                'DIRETORIA REGULARIZAÇÃO FUNDIÁRIA E COMPRA ASSISTIDA - DRF',
        
     ],
    'Jadson':[
        'DIRETORIA COMERCIAL - DCOM'
    ],
    'Sergio Oliveira':[
        'DIRETORIA COMERCIAL - DCOM' 
    ],
    'Marcelo Andrade':[
        'DIRETORIA DE SOCIOECONOMIA E ENGAJAMENTO - DES'
    ],
    'Marco Antonio':[
        'DIRETORIA ADMINISTRATIVA FINANCEIRA - DAF'
    ],
    'Jacqueline':[
        'DIRETORIA REGULARIZAÇÃO FUNDIÁRIA E COMPRA ASSISTIDA - DRF'
    ],
    'Juliana Trindade':[
        'DIRETORIA DE SOCIOECONOMIA E ENGAJAMENTO - DES'
    ],
    'Paola Ferreira':[
        'DIRETORIA DE DESLOCAMENTO INVOLUNTÁRIO E ANÁLISES TERRITORIAIS - DDIAT'
    ],
    'Fabio Moura':[
        'DIRETORIA DE DESLOCAMENTO INVOLUNTÁRIO E ANÁLISES TERRITORIAIS - DDIAT'
    ],
    'Carlos Longino':[
        'DIRETORIA DE DESLOCAMENTO INVOLUNTÁRIO E ANÁLISES TERRITORIAIS - DDIAT'
    ],
    'Adilson Fernandes':[
        'DIRETORIA DE SOCIOECONOMIA E ENGAJAMENTO - DES'
    ]
}

tipo_okr_list = [
    '1. Obter Resultados de Excelência',
    '2. Surpreender os Clientes em Todos os seus Mercados',
    '3. Melhorar a Eficiência Operacional de Toda a NMC',
    '4. Aprendizado e Crescimento',
]

id_app_list = [
    #'296',
    '289',
    '315',
    '290',
    '292',
    '282',
    '283',
    '320'
]

dic_formfield = {
    '289':['codUser',
            'responsavelPelaAtividadeval',
            'dataVencimentoDaTarefaGeral',
            'diretoria',
            'frequenciaDeMensuracao',
            'kR',
            'metaIndividualtab',
            'oKR',
            'periodo',
            'peso',
            'resultadoAlcancado',
            'tipoDeKRmeta',
            'tipoDeMedida'],
    '315':['codUser',
        'colaboradorResponsavel',
        'cumpriuAMetamoeda',
        'descricaoDaMetaMensal',
        'diretoria',
        'diretoriasQueParticipamDessaMeta',
        'discriminacaoDoResultadoobservacoesmoeda',
        'frequenciaDeMensuracao',
        'metaIndividual',
        'necessidadeDePlanoDeAcaomoeda',
        'nivelDeDesdobramento',
        'kR',
        'oKR',
        'periodo',
        'periodoDeAvaliacaomoeda',
        'peso',
        'prazoParaExecucaoRDN',
        'quemTrouxeOCliente-Gmmt',
        'resultadoAlcancado-Ykut',
        'resultadoAlcancadomoeda',
        'tipoDeKRmeta',
        'tipoDeMedida',
        'totalAcumulado'],
    '290':['escolhaOAno',
        'codUser',
        'colaboradorResponsavel',
        'responsavelPelaAtividadeval',
        'compartilharMetaEntreDiretorias',
        'descricao',
        'desdobramentos',
        'descricaoDaMetaMensal-Gduv',
        'descricaoDaMetaMensal',
        'diretoria',
        'diretoriasQueParticipamDessaMeta',
        'frequenciaDeMensuracao',
        'desdobramentoDoKR-DiretoriaComercial',
        'metaIndividualtab',
        'metaIndividual',
        'nivelDeDesdobramento',
        'kR',
        'oKR',
        'semTitulo',
        'periodo',
        'perspectiva',
        'peso',
        'prazoParaExecucaoRDN',
        'escolhaOSemestre',
        'tipoDeKRmeta',
        'tipoDeMedida',
        'escolhaOTrimestre'],
    '292':['codUser',
        'colaboradorResponsavel',
        'compartilharMetaEntreDiretorias',
        'cumpriuAMetamoeda',
        'cumpriuAMetaqtd',
        'cumpriuAMetaporc',
        'descricaoDaMetaMensal',
        'diretoria',
        'diretoriasQueParticipamDessaMeta',
        'discriminacaoDoResultadoobservacoesmoeda',
        'discriminacaoDoResultadoobservacoesentreg',
        'discriminacaoDoResultadoobservacoesqtd',
        'discriminacaoDoResultadoobservacoesporc',
        'frequenciaDeMensuracao',
        'metaIndividual',
        'necessidadeDePlanoDeAcaomoeda',
        'necessidadeDePlanoDeAcaoentreg',
        'necessidadeDePlanoDeAcaoqtd',
        'necessidadeDePlanoDeAcaoporc',
        'nivelDeDesdobramento',
        'kR',
        'oKR',
        'periodo',
        'periodoDeAvaliacaomoeda',
        'periodoDeAvaliacaoentreg',
        'periodoDeAvaliacaoqtd',
        'periodoDeAvaliacaoporc',
        'peso',
        'prazoParaExecucaoRDN',
        'resultadoAlcancado-Ykut',
        'resultadoAlcancadoporc',
        'resultadoAlcancadoQtd',
        'resultadoAlcancadomoeda',
        'resultadoAlcancadoSimnaoentreg',
        'tipoDeKRmeta',
        'tipoDeMedida',
        'totalAcumuladoporc',
        'totalAcumuladoqtd',
        'totalAcumulado'],
    '296':['escolhaOAno',
        'descrevaOQueFuncionouNoCiclo',
        'descrevaOQuePoderiaMelhorarNoProximoCiclo',
        'descricao',
        'duvidasEmRelacaoAoCicloAnterior',
        'ideiasParaAplicarAsMelhorias',
        'nomeDoOKR',
        'escolhaOPeriodo',
        'perspectiva',
        'escolhaOSemestre',
        'escolhaOTrimestre'],
    '282':['aprovarMetaSugerida',
        'codUser',
        'colaboradorResponsavel',
        'comoSeraFeito',
        'comoserafeitonovoplano',
        'cumpriuametaaposnovoplanodeacao',
        'cumpriuAMeta',
        'custo',
        'custonovoplano',
        'dataDeRevisaoDaMeta',
        'descricao',
        'metaAjustada',
        'metaSugeridaPeloAprovador',
        'nivelDeDesdobramento',
        'kR',
        'oKR',
        'oqueserafeitonovoplano',
        'oQueSeraFeito',
        'objetivonovoplanodeacao',
        'objetivoplanodecao',
        'periodo',
        'perspectiva',
        'prazo',
        'prazonovoplano',
        'prazoParaExecucaoRDN',
        'realizarOutroPlanoDeAcao',
        'responsavel',
        'responsavelnovoplano',
        'resultadoAlcancadoAposNovoPlanodeAcao',
        'resultadoAlcancadoPosPlanodeAcao',
        'revisaoDeMetaDentroDoPrazoRDN',
        'SolicitarRevisaodeMeta'],
    '283':['aprovarMetaSugerida',
        'codUser',
        'colaboradorResponsavel',
        'descricao',
        'justifiqueASolicitacao',
        'metaAjustada',
        'metaSugeridaPeloAprovador',
        'nivelDeDesdobramento',
        'kR',
        'oKR',
        'objetivoplanodecao',
        'periodo',
        'perspectiva'],
    '320':[
        'codUser',
        'responsavelPelaAtividadeval',
        'cumpriuAMetamoeda',
        'detalhamentoDaMetaGeralFaturamento',
        'detalhamentoDaMetaGeralLucroLiquido',
        'diretoria',
        'discriminacaoDoResultadoobservacoesmoeda',
        'frequenciaDeMensuracao',
        'metaGeralFaturamento',
        'metaGeralLucroLiquido',
        'necessidadeDePlanoDeAcaomoeda',
        'nomeDoArquivo',
        'contrato',
        'nomeDoDocumento',
        'kR',
        'oKR',
        'nomeDoResponsavel',
        'periodo',
        'periodoDeAvaliacaomoeda',
        'peso',
        'prazoParaExecucaoRDN',
        'resultadoAlcancado-Ykut',
        'resultadoAlcancadomoeda',
        'tipo',
        'tipoDeKRmeta',
        'totalAcumulado',
    ]

    }

